export const TREE_QUOTES = [
  "I'm rooting for you!",
  "Leaf me alone, I'm bushing!",
  "You're un-be-leaf-able!",
  'Branching out, are we?',
  "I'm stumped.",
  'Wood you like to hear a joke?',
  'Stay grounded.',
  "That's tree-mendous!",
  'Barking up the wrong tree?',
  'Turn over a new leaf.',
  'Why do we Ancients never get lost in the forest? ... Because we always stick to our roots.',
  'A Night Elf asked if I wanted to go to the inn. I told him... I was already board.',
  "I tried to be a Resto Druid once... but I just couldn't leave it alone.",
  'What is a Treant’s favorite school of magic? ... Log-ic.',
  'Why did the sapling get in trouble with the Cenarion Circle? ... He was being a little shady.',
  'Hrumph. I defeated a Goblin Shredder yesterday. ... I stumped him.',
  'Why was the Ancient of War always hired for the job? ... Because he really knew how to branch out.',
  'Do not ask me for spare gold, little one. ... I only have silver-leaf.',
  "What did the Druid say when he shifted into a tree form during the raid? ... 'I am rooted in my decision.'",
  'Why do we hate the Barrens? ... There is nowhere to hide.',
  'I once dated a Dryad... but there was no spark. Only kindling.',
  'What is an Ancient’s favorite dungeon? ... The Stem vault.',
  'Why was the willow tree crying in Moonglade? ... It wanted to be a Weeping Willow, but it was just a regular one.',
  "I asked the Archdruid how to get to Nordrassil. He said... 'Just lumber along until you see it.'",
  'Why do Treants make terrible rogues? ... Because our bark is worse than our bite, and we creak when we sneak.',
  'Hooom. A Peon tried to chop me down. ... I told him to axe me nicely first.',
  'What do you call a Treant who talks too much in world chat? ... A Chatter-oak.',
  'Why did the Ancient break up with the flower? ... She was a blooming idiot.',
  'How do we access the Emerald Dream? ... We just log in.',
  "Remember, little mortals... if you want to be strong like me... don't skip leg day. Or as I call it... trunk day.",
]
